<a href="https://colab.research.google.com/github/Jeet2561/13sep_Jeet/blob/main/Matrix_Multiplication_and_Tensor_aggregations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

####To fix our tensor shape issues, we can manipulate the shape of one of our tensors using Transpose

In [9]:
tensor_B.shape

torch.Size([3, 2])

In [10]:
# Transpose of tensor_B
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [11]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

##Finding the min, max, mean, sum, etc. (tensor aggregation)

In [12]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
# Min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [15]:
# Max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [18]:
# Mean - For mean the tensor should have either float values or complex dtypes...
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [19]:
# Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [20]:
# argmin - Returns the index number of the minimum value
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [21]:
# argmax - Return the index number if the maximum value
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))