<a href="https://colab.research.google.com/github/Jeet2561/13sep_Jeet/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


##Introduction to Tensors
###Creating Tensors

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as a python int
scalar.item()

7

In [11]:
# Vector
vector = torch.tensor([7,7])
vector
vector.ndim
vector.shape

torch.Size([2])

In [13]:
# MATRIX
matrix = torch.tensor([[1,2],[3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [14]:
matrix.ndim

2

In [16]:
matrix[0]

tensor([1, 2])

In [17]:
matrix.shape

torch.Size([2, 2])

In [18]:
# TENSOR
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

#Random Tensors

###Why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and thne adjust those random numbers to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at data -> update random numbers`

In [21]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9639, 0.9007, 0.8669, 0.1039],
        [0.2483, 0.7327, 0.7824, 0.9307],
        [0.4187, 0.0895, 0.1551, 0.6680]])

In [22]:
random_tensor.ndim

2

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [24]:
# Creating a random tensor (Practice)
random_TENSOR = torch.rand(1, 3, 3)
random_TENSOR

tensor([[[0.2574, 0.7889, 0.1841],
         [0.2082, 0.5992, 0.5201],
         [0.1729, 0.4689, 0.1453]]])

In [25]:
random_TENSOR.ndim , random_TENSOR.shape

(3, torch.Size([1, 3, 3]))

#Zeros and Ones

In [26]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Creating a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

# Creating a Tensor in range and tensors-like

In [31]:
# Use torch.arange
tensor_in_range = torch.arange(0,10)
tensor_in_range

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])