<a href="https://colab.research.google.com/github/Jeet2561/13sep_Jeet/blob/main/pytorch_tensor_attribute.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Getting information from the tensor


1.   Tensors not right datatype - to get the datatype from the tensor, use `torch.dtype`.
2.   Tensors not right shape - to get shape from the tensor, use `tensor.shape`.
3.   Tensors not on the right device - to get the device from the tensor, use `tensor.device`.



In [2]:
# Create a tensor
tensor = torch.rand(3,4)
tensor

tensor([[0.8592, 0.9667, 0.0375, 0.0257],
        [0.9576, 0.6657, 0.2111, 0.6142],
        [0.6001, 0.7050, 0.9507, 0.5562]])

In [3]:
# Details of the tensor
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Device of tensor: {tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


#Manipulating Tensor (Tensor operations)

Tensor operations include :


*   Addition

*   Subtraction
*   Multiplication (element-wise)


*   Division
*   Matrix multiplication



In [4]:
# Create a tensor and add 10 to it.
tensor = torch.tensor([4,5,6])
tensor + 10

tensor([14, 15, 16])

In [5]:
# Multiply by 10
tensor * 10

tensor([40, 50, 60])

In [6]:
# Subtarct 10
tensor - 10

tensor([-6, -5, -4])

In [9]:
# PyTorch in-built functions
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10))
print(torch.mul(tensor, 10))
print(torch.div(tensor, 10))

tensor([14, 15, 16])
tensor([-6, -5, -4])
tensor([40, 50, 60])
tensor([0.4000, 0.5000, 0.6000])


In [10]:
# Element-wise multiplication
print(tensor ,"*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([4, 5, 6]) * tensor([4, 5, 6])
Equals : tensor([16, 25, 36])


In [15]:
# Matrix multiplication (dot product)
test1 = torch.tensor([[1,2,3],
                      [4,5,6]])

test2 = torch.tensor([[7,8],
                      [9,10],
                      [11,12]])

torch.matmul(test1, test2)

tensor([[ 58,  64],
        [139, 154]])